<html xmlns="http://www.w3.org/1999/xhtml">  
<head> 
	<meta http-equiv="Content-Type" content="text/html;charset=utf8" />  
	<title>apidb_test</title>
	<style>
		.a_input {
			width:300px;
		}
		.a_textarea {
			width:100%;
			height:100px;
		}	
		.b_textarea {
			width:100%;
			height:400px;
		}
	</style>
	<script src='https://lib.sinaapp.com/js/jquery/1.8/jquery.min.js' charset='utf-8'></script>
	<script type="text/javascript" charset='utf-8'>
	var API_CONFIG = 
	{
		"ad_list":{
			"name":"广告列表",
			"url":"/ad/ass201306.json",
			"method":"get",
			"params":"app_code=111&tag_code=kikitag&page=1&count=10"
		},
			
		"hit_log":{
			"name":"点击日志",
			"url":"/click/ass201306.json",
			"method":"get",
			"params":"tag_code=kikitag&app_code=111&mac=-mac-&idfa=-idfa-&idfv=-idfv-&imei=-imei-&phone=-phone-&ad_id=478"
		},
		"web_back":{
			"name":"回调广告主接口",
			"url":"/webback/ass201306.json",
			"method":"get",
			"params":""
		}		
	}
	</script>
</head>
<body>
	<p>
	<label>接口名称：</label>
	<select name="request">
	</select>&nbsp;&nbsp;
	<label>接口地址：</label>
	<input type="text" class="a_input" name="request_url" value="/" />&nbsp;&nbsp;
	<label>方法类型：</label>
	<select name="request_method">
		<option value="get">get</option>
		<option value="post">post</option>
	</select>&nbsp;&nbsp;
	<input type="submit" id="request_send" value="send"/>
	</p>
	<p>
		<label>参数：</label><textarea class="a_textarea" name="request_params"></textarea>
	</p>
	<p>
		<label>结果：</label><textarea class="b_textarea" name="request_reponse"></textarea>
	</p>
	<script type="text/javascript">
		$(function() {
			for (var k in API_CONFIG) {
				$('select[name="request"]').append('<option value="'+k+'">'+API_CONFIG[k].name+'</option>');
			}
			$('#request_send').click(function() {
				var url = $('input[name="request_url"]').val();
				var method = $('select[name="request_method"]').val();
				var params = $('textarea[name="request_params"]').val();
				var type = $('select[name="request_type"]').val();

				$.ajax({
				   type: method,
				   url: '/adapi'+url,
				   data: params,
				   dataType: 'json',
				   contentType: 'application/x-www-form-urlencoded',
				   async: false,
				   success: function(data){
					   var data = JSON.stringify(data);
				       $('textarea[name="request_reponse"]').val(data);
				   }
				});
			});
			$('select[name="request"]').change(function() {
				set($(this).val());
			});
			set('ad_list');
		});

		function set(k)
		{
			$('input[name="request_url"]').val(API_CONFIG[k].url);
			var method = API_CONFIG[k].method;
			$('option[value="'+method+'"]').attr('selected', '1');
			var str = JSON.stringify(API_CONFIG[k].params).replace(/(^")|("$)/g, "");
			$('textarea[name="request_params"]').val(str);
		}
	</script>
</body>
</html>
